#================================================================
#   Copyright (C) 2020 Sangfor Ltd. All rights reserved.
#   文件类型：Makefile脚本
#   文件名称：Makefile
#   创 建 者：Chenlvqing
#   创建日期：2020年03月25日
#   描    述：
#
#================================================================

#OBJ = $(wildcard *.c *.h)
#all:
#	@echo $(OBJ)

OBJ1 = $(wildcard *.sh)
all:
	@echo $(OBJ1)
